---
title: Baseball Hall of Fame"
author: "Amisha Jain"
date: '2022-06-28'
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(rvest)
```


```{r wiki_get, echo = FALSE}
hof_url <- "https://en.wikipedia.org/wiki/List_of_members_of_the_Baseball_Hall_of_Fame"

table_tags <- hof_url |> 
  read_html() |> 
  html_elements("table") |> 
  html_table()
```


```{r table, echo = FALSE}
#clean up data below
graph_data <- table_tags[[3]] |> 
  rename(year = Year, name = Name) |> 
  mutate(year = as.character(year)) |> 
  mutate(year = ifelse(nchar(year) > 4, substr(year, 1, 4), year)) |> 
  mutate(year = parse_number(year))
```

```{r, echo = FALSE}
graph_data |> 
  ggplot(aes(x = year))  +
    geom_bar() + theme_classic() +
  labs(title = "Baseball Hall of Fame Inductions", 
       subtitle = "Spike in 2006 associated with Negro League inclusion", 
       x = "Year", 
       y = "Number of Inductees", 
       caption = "Data: Wikipedia")
```


